


DROP TABLE IF EXISTS Rundholz,Schnittholz,bestellung, rechnung,auftrag,aufgabe;

create table Rundholz(
box_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
wood_type varchar(50) NOT NULL,
festmeter double NOT NULL CHECK(festmeter >0),
amount integer NOT NULL CHECK(amount>0),
length integer NOT NULL CHECK(length>0),
quality varchar(10) NOT NULL,
diameter integer NOT NULL CHECK(diameter>0),
price integer NOT NULL CHECK(price>0),
last_edited Timestamp NOT NULL DEFAULT CURRENT_DATE());

create table Schnittholz(
schnittID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
lager varchar(30) NOT NULL,
description varchar(50) NOT NULL,
finishing varchar(30) NOT NULL,
wood_type varchar(20) NOT NULL,
quality varchar(20) NOT NULL,
size integer NOT NULL CHECK(size>0),
width integer NOT NULL CHECK(width>0),
length integer NOT NULL CHECK(length>0),
quantity integer NOT NULL CHECK(quantity>0),
reserved_quantity integer NOT NULL CHECK(reserved_quantity>0),
delivered_quantity integer NOT NULL CHECK(delivered_quantity>0),
all_reserved boolean NOT NULL,
all_delivered boolean NOT NULL);

create table bestellung(
bestellNr integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
kundenname varchar(50),
wood_type varchar(10),
amount integer NOT NULL CHECK(amount>0),
quantity integer NOT NULL CHECK(quantity>0),
schnittID integer REFERENCES schnittholz(schnittID),
duedate Timestamp NOT NULL DEFAULT CURRENT_DATE(),
summe integer NOT NULL,
isDoneFlag boolean NOT NULL);

create table auftrag(
Nr integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
description varchar(50) NOT NULL,
finishing varchar(15) NOT NULL,
wood_type varchar(15) NOT NULL,
quality varchar(15) NOT NULL,
size integer NOT NULL CHECK(size>0),
width integer NOT NULL CHECK(width>0),
length integer NOT NULL CHECK(length>0),
quantity integer NOT NULL CHECK(quantity>0),
produced_quantity integer NOT NULL CHECK(produced_quantity>0),
bestellNr integer REFERENCES bestellung(bestellNr),
done boolean NOT NULL,
deleted boolean NOT NULL);

create table aufgabe(
Nr integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
eingang Timestamp NOT NULL DEFAULT CURRENT_DATE(),
RH_boxNr integer NOT NULL CHECK(RH_boxNr>0),
RH_menge integer NOT NULL CHECK(RH_menge>0),
auftragNr integer REFERENCES auftrag(auftragNr),
markiert boolean NOT NULL);

create table rechnungen(
rechnungsNr integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
kundenname varchar(50),
artikelbeschreibung varchar(10),
preis integer NOT NULL CHECK(preis>0),
anzahlauftraege integer NOT NULL CHECK(anzahlauftraege>0),
anzahlstueck_gesamt integer NOT NULL CHECK(anzahlstueck_gesamt>0),
rechnungsdatum Timestamp NOT NULL DEFAULT CURRENT_DATE(),
betragBrutto integer NOT NULL CHECK(betragBrutto>0),
Mwst varchar(20)NOT NULL,
betragNetto integer NOT NULL CHECK (betragNetto>0),
status varchar(30) NOT NULL,
zahlungart boolean NOT NULL,
totalbetrag integer NOT NULL CHECK(totalbetrag>0));

INSERT INTO rundholz(wood_type,festmeter,amount,length, quality,diameter,price,last_edited) VALUES
('Fichte', 21.28,7,3500, 'CX', 220,50,now()),
('Fichte', 21.28,7,3000, 'CX', 220,50,now()),
('Fichte', 21.28,5,2500, 'FX', 370,70,now()),
('Lose', 203.35,7,3500, 'FX', 240,80,now()),
('Polter',200.28,10,4000, 'FH', 220,100,now()),
('Fichte', 35.40,7,5000, 'FH', 300,50,now()),
('Polter', 123.20,7,1500, 'Bb', 220,50,now()),
('Lose', 55.89,17,4000, 'CX', 159,50,now()),
('Fichte', 21.28,19,5500, 'Bb', 220,50,now()),
('Fichte', 62.98,8,6000, 'CX', 180,200,now());

INSERT INTO schnittholz(lager,description,finishing,wood_type,quality,size,
width,length,quantity,reserved_quantity,delivered_quantity,
all_reserved,all_delivered) VALUES
('Lager1', 'Latten', 'Prismiert','Ta', 'I/III', 22,48,3000,40,50,42,1,0),
('Lager1', 'Staffel', 'Prismiert','Ta', 'II/IV', 22,48,2000,40,50,42,1,0),
('Lager1', 'Kantholz', 'Prismiert','Fi/Ta', 'I/III', 22,48,5000,40,100,50,1,1),
('Lager1', 'Schnittholz','Prismiert','Ta','S10/CE/TS', 22,48,1000,40,50,42,1,0),
('Lager1', 'Latten', 'roh-SW','Fi', 'I/III', 22,48,3000,40,50,42,1,0),
('Lager1', 'Staffel', 'roh-SW','Ta', 'S10/CE/TS', 22,48,6000,40,50,42,1,0),
('Lager1', 'Kantholz', 'roh-SW','Fi', 'II/IV', 22,48,2500,40,50,42,1,0),
('Lager1', 'Schnittholz', 'roh-SW','Fi/Ta', 'I/III', 22,48,2100,40,50,42,1,0),
('Lager1', 'Latten', 'Prismiert','Ta', 'I/III', 22,48,1500,40,50,42,1,0),
('Lager1', 'Latten', 'roh','Ta', 'S10/CE/TS', 22,48,3000,40,60,60,0,1);

INSERT INTO bestellung(kundenname,wood_type,amount,quantity,
schnittID, duedate,summe, isDoneFlag) VALUES
('Herr Fischer', 'Ta',2,100,1,now(), 250,1),
('Frau M¸ller', 'Fi',3,200,2,now(),320,0),
('Herr Fadinger', 'Ta',1,30,4,now(),90,0),
('Herr M¸ller', 'Fi/Ta',3,200,2,now(),100,0),
('Frau Korz',  'Fi',2,90,5,now(),130,1),
('Herr Girtler', 'Ta',3,200,8,now(),95,1),
('Frau Mooner', 'Fi/Ta',3,210,7,now(),200,0),
('Frau Digner', 'Fi',3,200,2,now(),261,0),
('Herr Bossack', 'Ta',3,200,2,now(),320,1),
('Herr Klima', 'Fi',3,200,2,now(),254,1),

INSERT INTO rechnungen(kundenname,artikelbeschreibung,preis,anzahlauftraege,
anzahlstueck_gesamt,rechnungsdatum,betragBrutto,Mwst,betragNetto,status,zahlungart,totalbetrag) VALUES
('Herr Fischer', 'Ta',23,2,34,now(),50,'17%', 453,'provisorich',1,345),
('Frau M¸ller', 'Fi',33,2,200,now(),32,'19%', 267,'definitiv',0,567),
('Herr Klima', 'Ta',23,2,34,now(),50,'17%', 453,'provisorich',1,345),
('Frau Bosak', 'Fi',33,2,200,now(),32,'19%', 267,'definitiv',0,567),
('Herr Kors', 'Ta',23,2,34,now(),50,'17%', 453,'provisorich',1,345),
('Frau Girtler', 'Fi',33,2,200,now(),32,'19%', 267,'definitiv',0,567),
('Herr Mooner', 'Ta',23,2,34,now(),50,'17%', 453,'provisorich',1,345),
('Frau Digner', 'Fi',33,2,200,now(),32,'19%', 267,'definitiv',0,567);

INSERT INTO auftrag(description,finishing,wood_type,quality,size,
width,length,quantity,produced_quantity, bestellNr,done,deleted) VALUES
('Latten','Prismiert','Ta', 'I/III', 22,48,3000,40,50,1,0,0),
('Staffel','Prismiert','Ta', 'II/IV', 22,50,2000,40,50,1,0,0),
('Kantholz','Prismiert','Fi/Ta','I/III',22,48,5000,40,100,1,1,0),
('Schnittholz','Prismiert','Ta','S10/CE/TS',22,48,900,40,50,1,0,0),
('Latten','roh-SW','Fi', 'I/III', 22,48,3000,40,50,1,0,0),
('Staffel','roh-SW','Ta','S10/CE/TS',22,48,6000,40,70,5,0,0),
('Kantholz','roh-SW','Fi', 'II/IV', 22,48,2500,40,42,1,0,0),
('Schnittholz','roh-SW','Fi/Ta','I/III',22,48,2100,40,50,3,0,0),
('Latten','Prismiert','Ta', 'I/III', 22,48,1500,40,42,1,0,0),
('Latten','roh','Ta', 'S10/CE/TS', 22,48,3000,40,80,2,1,0);

INSERT INTO aufgabe(Eingang,RH_boxNr, RH_menge,AuftragNr, Markiert) VALUES
(now(),2,3,4,0),
(now(),5,2,4,1),
(now(),5,6,5,0),
(now(),8,4,2,1),
(now(),2,3,2,0),
(now(),8,2,2,1),
(now(),9,3,3,1),
(now(),7,4,3,0),
(now(),6,3,3,0),
(now(),4,2,4,1);





