CREATE TABLE IF NOT EXISTS LUMBER (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ORDERDATE TIMESTAMP NOT NULL,
  ISPAID BIT DEFAULT 0,
  DELETED BIT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TASK (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ORDERID INT NOT NULL,
  DESCRIPTION VARCHAR(50),
  FINISHING VARCHAR(15),
  WOOD_TYPE VARCHAR(10),
  QUALITY VARCHAR(10),
  SIZE INT NOT NULL,
  WIDTH INT NOT NULL,
  LENGTH INT NOT NULL,
  QUANTITY INT,
  PRODUCED_QUANTITY INT,
  DONE BIT DEFAULT 0,
  DELETED BIT DEFAULT 0,
  FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID)
);

MERGE INTO ORDERS (ID, ORDERDATE, DELETED) KEY(ID) VALUES(1, '2017-12-03 08:00:00', 0);

MERGE INTO TASK (ID, ORDERID, DESCRIPTION, SIZE, WIDTH, LENGTH, QUANTITY, PRODUCED_QUANTITY, DONE) KEY(ID) VALUES(1, 1, 'for testing purpose only', 24, 48, 3000, 10, 10, 1);
MERGE INTO TASK (ID, ORDERID, DESCRIPTION, SIZE, WIDTH, LENGTH, QUANTITY, PRODUCED_QUANTITY, DONE) KEY(ID) VALUES(1, 1, 'another test', 28, 100, 300, 20, 20, 1);